# Sistema de recompensas

In [23]:
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import set_random_seed
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.metrics import mean_squared_error, r2_score, max_error
from sklearn.linear_model import LinearRegression
from statsmodels.tsa.seasonal import seasonal_decompose

***Read Data***

In [34]:
X_train = pd.read_csv('../data/interim/bicimad_Xtrain_X.csv', sep=',')
X_test = pd.read_csv('../data/interim/bicimad_Xtest_X.csv', sep=',')
y_train = pd.read_csv('../data/interim/bicimad_ytrain_X.csv', sep=',')
y_test = pd.read_csv('../data/interim/bicimad_ytest_X.csv', sep=',')

# Neural Networks

In [16]:
set_random_seed(42)

model = Sequential()
model.add(Dense(12, input_dim=9, activation='relu'))
model.add(Dense(1, activation='softmax'))

In [17]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model

In [18]:
model.fit(X_train, y_train, epochs = 50, batch_size = 10)

Epoch 1/50


/home/vscode/.local/lib/python3.11/site-packages/tensorflow/python/util/dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(10, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


4800/4800 [==============================] - 5s 883us/step - loss: nan - accuracy: 5.6250e-04
Epoch 2/50
4800/4800 [==============================] - 4s 848us/step - loss: nan - accuracy: 5.6250e-04
Epoch 3/50
4800/4800 [==============================] - 4s 875us/step - loss: nan - accuracy: 5.6250e-04
Epoch 4/50
4800/4800 [==============================] - 4s 873us/step - loss: nan - accuracy: 5.6250e-04
Epoch 5/50
4800/4800 [==============================] - 4s 863us/step - loss: nan - accuracy: 5.6250e-04
Epoch 6/50
4800/4800 [==============================] - 4s 833us/step - loss: nan - accuracy: 5.6250e-04
Epoch 7/50
4800/4800 [==============================] - 4s 866us/step - loss: nan - accuracy: 5.6250e-04
Epoch 8/50
4800/4800 [==============================] - 4s 868us/step - loss: nan - accuracy: 5.6250e-04
Epoch 9/50
4800/4800 [==============================] - 4s 876us/step - loss: nan - accuracy: 5.6250e-04
Epoch 10/50
4800/4800 [==============================] - 4s 870us/

In [19]:
_, accuracy = model.evaluate(X_train, y_train)

print(f"Accuracy: {accuracy}")

   1/1500 [..............................] - ETA: 2:39 - loss: nan - accuracy: 0.0000e+00

 117/1500 [=>............................] - ETA: 1s - loss: nan - accuracy: 0.0011     

/home/vscode/.local/lib/python3.11/site-packages/tensorflow/python/util/dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


1500/1500 [==============================] - 1s 807us/step - loss: nan - accuracy: 5.6250e-04
Accuracy: 0.0005624999757856131


In [20]:
y_pred = model.predict(X_test)
y_pred[:15]

 71/375 [====>.........................] - ETA: 0s 

375/375 [==============================] - 0s 734us/step


array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [21]:
y_pred_round = [round(x[0]) for x in y_pred]
y_pred_round[:15]

ValueError: cannot convert float NaN to integer

In [22]:
accuracy_score(y_test, y_pred_round)

NameError: name 'y_pred_round' is not defined

# Decission Tree

In [33]:
model = DecisionTreeRegressor(random_state = 42)
model.fit(X_train, y_train)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Float64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>)

In [26]:
fig = plt.figure(figsize=(15,15))

tree.plot_tree(model, feature_names = list(X_train.columns), class_names = ["0", "1", "2"], filled = True)

plt.show()

KeyboardInterrupt: 

In [41]:
y_pred = model.predict(X_test)
y_pred

array([  6., 118.,  93., ..., 113.,  22.,  23.])

In [42]:
print(f"Error cuadrático medio: {mean_squared_error(y_test, y_pred)}")

Error cuadrático medio: 2376.4192377495465


In [43]:
max_error(y_test, y_pred)

116.0

In [45]:
y_test

trip_minutes
0               52
1               89
2               28
3               39
4                6
...            ...
1097           119
1098            25
1099            39
1100            15
1101            28

[1102 rows x 1 columns]

# Linear Regression

In [48]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [49]:
print(f"Intercepto (a): {model.intercept_}")
print(f"Coeficientes (b): {model.coef_}")

Intercepto (a): [54.54760501]
Coeficientes (b): [[ 0.00089707  0.0759325  -0.06778498  0.00869273 -0.0910053   0.04749374
   0.12771111  0.04749374 -0.00087297]]


In [50]:
y_pred = model.predict(X_test)
y_pred

array([[60.13001693],
       [59.47833631],
       [58.48346375],
       ...,
       [56.42877508],
       [62.17418275],
       [61.43944602]])

In [52]:
print(f"Error cuadrático medio: {mean_squared_error(y_test, y_pred)}")
print(f"Coeficiente de determinación: {r2_score(y_test, y_pred)}")

Error cuadrático medio: 1182.843519767521
Coeficiente de determinación: -0.00840069531386578


# Time Series

In [35]:
X_train['unlock_date'] = pd.to_datetime(X_train['unlock_date'])

In [36]:
X_train

idDriver_n  idBike  fleet unlock_date  unlock_hour  latitude_unlock  \
0            4299    2174      1  2022-04-26            7         40.43503   
1            3230    5013      1  2022-04-20           23         40.39817   
2            8048    6381      1  2022-04-07           20         40.39288   
3            9798    6639      1  2022-04-19           15         40.41467   
4           13704    5146      1  2022-04-17           21         40.39178   
...           ...     ...    ...         ...          ...              ...   
47995       15762    7353      1  2022-04-28            2         40.43528   
47996        7636    2679      1  2022-04-20           18         40.41825   
47997         820    7463      1  2022-04-01            8         40.44421   
47998        6778    7878      1  2022-04-08           13         40.41975   
47999        8503    6277      1  2022-04-29           15         40.41080   

       longitude_unlock  station_unlock  dock_unlock  unlock_station_name_n  \
0              -3.67012             251           24                     63   
1              -3.70239             181            2                     85   
2              -3.69757             135            7                    117   
3              -3.70368              38           19                    141   
4              -3.70267             230            8                     99   
...                 ...             ...          ...                    ...   
47995          -3.69486             164            3                      4   
47996          -3.67661             189           22                      8   
47997          -3.66683             259           21                    237   
47998          -3.68839              64           17                      6   
47999          -3.71411              41            4                    201   

       ... dock_lock  lock_station_name_n  distance  trip_speed  \
0      ...         4                  254  3.419847    0.206263   
1      ...         5                   23  2.150848    0.198601   
2      ...         3                   69  1.684720    0.294017   
3      ...        18                  187  2.699207    0.225875   
4      ...        22                   89  1.581007    0.127501   
...    ...       ...                  ...       ...         ...   
47995  ...         7                    5  3.653833    0.225964   
47996  ...         6                  124  3.755455    0.158258   
47997  ...        18                  239  2.218377    0.053844   
47998  ...        19                  244  4.274663    0.216110   
47999  ...        26                  133  1.428832    0.031787   

       trip_day_of_week_n  trip_duration_category_n  station_unlock_count  \
0                       4                         1                   183   
1                       5                         0                   279   
2                       6                         0                   432   
3                       4                         0                   309   
4                       2                         0                   241   
...                   ...                       ...                   ...   
47995                   6                         1                   308   
47996                   5                         1                   383   
47997                   0                         2                   172   
47998                   0                         1                   484   
47999                   0                         2                   454   

       station_lock_count  travel_direction_n  lock_unlock_time_gap_hours  
0                      71                   0                         0.0  
1                     550                   0                         0.0  
2                     260                   0                         0.0  
3                     235                   1                         0.0  
4          